using System.Runtime.InteropServices;

namespace Drones.ARDrone.Client.Navdata.Native.Common
{
    [StructLayout(LayoutKind.Sequential, Pack = 1, CharSet = CharSet.Ansi)]
    public struct navdata_video_stream_t
    {
        public ushort tag;
        public ushort size;

        /// <summary> Quantizer reference used to encode frame [1:31]. </summary>
        public byte quant;

        /// <summary> Frame size (bytes) </summary>
        public uint frame_size;

        /// <summary> Frame index. </summary>
        public uint frame_number;

        /// <summary> Atmcd ref sequence number. </summary>
        public uint atcmd_ref_seq;

        /// <summary> Mean time between two consecutive atcmd_ref (ms) </summary>
        public uint atcmd_mean_ref_gap;

        public float atcmd_var_ref_gap;

        /// <summary> Estimator of atcmd link quality. </summary>
        public uint atcmd_ref_quality;

        /// <summary> Measured out throughput from the video tcp socket. </summary>
        public uint out_bitrate;

        /// <summary> Last frame size generated by the video encoder. </summary>
        public uint desired_bitrate;

        public int data1;
        public int data2;
        public int data3;
        public int data4;
        public int data5;

        public uint tcp_queue_level;
        public uint fifo_queue_level;
    }
}
